# sudo always required with Docker
sudo: required
services:
    - docker

before_install:
    - docker build -t jmlinder/docker-proj -f Dockerfile.dev .

# npm run test does not exit, so need to implement the -- --coverage flag to end the test
script:
    - docker run -e CI=true jmlinder/docker-proj npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    access_key_id:
        secure: "$access_key_id"
    secret_access_key:
        secure: "$secret_access_key"
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-new"
    bucket_name: "elasticbeanstalk-us-east-1-835178066609"
    on:
        branch: master