FROM node:alpine

WORKDIR '/app'

COPY package.json .

RUN npm install

# COPY . . not needed when using -v / volumes: arguments,
# however it is good to leave in out o habit.
COPY . . 

CMD npm run start